# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-03 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passerelle_imio_sso_agents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imiossoagents',
            name='locality_name',
            field=models.CharField(blank=True, default=b'', max_length=128, verbose_name='Locality name'),
        ),
        migrations.AddField(
            model_name='imiossoagents',
            name='locality_slug',
            field=models.CharField(blank=True, default=b'', max_length=128, verbose_name='Locality slug (enterprise number)'),
        ),
    ]
