# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-04 11:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passerelle_imio_sso_agents', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImioAesMeal',
            new_name='ImioSsoAgents',
        ),
    ]
