# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-04 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passerelle_imio_sso_agents', '0002_auto_20190604_1357'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imiossoagents',
            options={'verbose_name': "Expose Agents CSV to valid JSON that be comsumme by Entr'ouvert"},
        ),
        migrations.AlterField(
            model_name='imiossoagents',
            name='meal_file',
            field=models.FileField(help_text='Supported file formats: csv', upload_to=b'agents_csv', verbose_name='Agents csv file'),
        ),
    ]
