# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-02 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passerelle_imio_sso_agents', '0003_auto_20190604_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imiossoagents',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='_imiossoagents_users_+', related_query_name='+', to='base.ApiUser'),
        ),
    ]
